/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2025-03-07 07:22:22 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mbr.req.project;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class projectList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(6);
    _jspx_dependants.put("/WEB-INF/lib/spring-security-taglibs-4.2.12.RELEASE.jar", Long.valueOf(1709100854305L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/spring-security-taglibs-4.2.12.RELEASE.jar!/META-INF/security.tld", Long.valueOf(1554198614000L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1709100854747L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fvar_005faccess_005fnobody;
  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fvar_005faccess_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.release();
    _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.release();
    _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fvar_005faccess_005fnobody.release();
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      if (_jspx_meth_sec_005fauthorize_005f0(_jspx_page_context))
        return;
      out.write('\r');
      out.write('\n');
      if (_jspx_meth_sec_005fauthorize_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("<head>\r\n");
      out.write("	<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("	<meta http-equiv=\"X-UA-Compatible\" content=\"IE=Edge\">\r\n");
      out.write("	<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" name=\"viewport\" />\r\n");
      out.write("	<meta content=\"\" name=\"description\" />\r\n");
      out.write("	<meta content=\"\" name=\"author\" />\r\n");
      out.write("	");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("	<title>KEPCO Cloud Service Platform</title>\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("	<!-- begin #page-container -->\r\n");
      out.write("	<div id=\"page-container\" class=\"fade page-container page-header-fixed page-sidebar-fixed page-with-footer\">\r\n");
      out.write("		<!-- begin #header -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<!-- end #header -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- begin #sidebar -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<!-- end #sidebar -->\r\n");
      out.write("		\r\n");
      out.write("		<!-- begin #content -->\r\n");
      out.write("		<div id=\"content\" class=\"content\">\r\n");
      out.write("			\r\n");
      out.write("			<p class=\"page_title\">프로젝트 요청현황\r\n");
      out.write("				<span class=\"root f14\">Home <span class=\"arrow_ab\"> &#8227; </span><a href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wasPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/main\"> 콘솔</a>  <span class=\"arrow_ab\"> &#8227; </span> 신청 현황  <span class=\"arrow_ab\"> &#8227; </span> <b> 프로젝트 요청 현황 </b>\r\n");
      out.write("			    </span>\r\n");
      out.write("			</p>\r\n");
      out.write("			\r\n");
      out.write("			<!-- begin page-body -->\r\n");
      out.write("			<div class=\"row p20 bgwh br10\">\r\n");
      out.write("	\r\n");
      out.write("			   <div class=\"explain_box\">\r\n");
      out.write("					<!-- <p class=\"icon\"><img src=\"/resources/assets/img/icon_mic.png\" /></p> -->\r\n");
      out.write("					<p class=\"text\"> &#183; 프로젝트는 개발(운영)되는 정보/업무 시스템을의미하며  시스템 자원(서버, 디스크)을 신청하기전에 가장 먼저 등록(신청)해야 합니다 . <br/>&#183; 독립된 프로젝트별로 생성된 시스템 자원은 논리적으로 완벽히 분리되어 운영됩니다. 서버들은 특정 프로젝트 안에서만 생성되며 논리적으로 완벽히 분리되어 있습니다.</p>\r\n");
      out.write("			   </div>\r\n");
      out.write("			\r\n");
      out.write("			<div class=\"card_contents_wrap\" id=\"cardList\">\r\n");
      out.write("			</div>\r\n");
      out.write("				\r\n");
      out.write("			<!-- 기존파일 -->	\r\n");
      out.write("			<!-- 테이블시작 -->\r\n");
      out.write("			<div class=\"col-md-12\">\r\n");
      out.write("				<input type=\"hidden\" id=\"roles\" value=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${roles}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\">\r\n");
      out.write("				<div class=\"panel\">\r\n");
      out.write("				    <div class=\"table-responsive\">\r\n");
      out.write("				        <table class=\"table table-bordered table-hover table-striped table-td-valign-middle\" id=\"mbrProjectOkList\">\r\n");
      out.write("							\r\n");
      out.write("\r\n");
      out.write("						</table>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>			\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- // 기존파일 -->\r\n");
      out.write("			\r\n");
      out.write("			</div>\r\n");
      out.write("			\r\n");
      out.write("			<!-- begin #footer -->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fimport_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<!-- end #footer -->\r\n");
      out.write("			\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- end #content -->\r\n");
      out.write("		\r\n");
      out.write("	</div>\r\n");
      out.write("	<!-- end page container -->\r\n");
      out.write("	\r\n");
      if (_jspx_meth_c_005fimport_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\r\n");
      out.write("	function gridList() {\r\n");
      out.write("		\r\n");
      out.write("		$(\"#mbrProjectOkList\").dataTable( { \r\n");
      out.write("// 		$(\"#cardList\").dataTable( { \r\n");
      out.write("				\"processing\":true\r\n");
      out.write("				,\"ordering\" : true\r\n");
      out.write("				,\"destroy\" : true\r\n");
      out.write("				,\"autoWidth\":false\r\n");
      out.write("				,\"serverSide\":true\r\n");
      out.write("			,\"ajax\": {\r\n");
      out.write("				\"url\":\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wasPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/req/project/projectList\"\r\n");
      out.write("				,\"type\" : \"GET\"\r\n");
      out.write("				,\"dateSrc\" : \"\"\r\n");
      out.write("				,\"data\":function (d) {\r\n");
      out.write("					d.searchKind = $(\"#searchKind > option:selected\").val();\r\n");
      out.write("					d.keyword = $(\"#keyword\").val();\r\n");
      out.write("				}\r\n");
      out.write("				,\"complete\" : function(obj, status){\r\n");
      out.write("					if(status == 'success'){\r\n");
      out.write("						setCardList(obj.responseJSON);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("	\r\n");
      out.write("			}\r\n");
      out.write("			, \"initComplete\" : function(setting, json){\r\n");
      out.write("				$(\"#mbrProjectOkList > thead\").remove();\r\n");
      out.write("				$(\"#mbrProjectOkList > tbody\").remove();\r\n");
      out.write("			}\r\n");
      out.write("			,\"columns\":[\r\n");
      out.write("			        	//{\"data\":\"projectName\", \"class\":\"tac\"}\r\n");
      out.write("			        	 {\"data\":\"customerName\",\"class\":\"tac\"} \r\n");
      out.write("						, {\"data\":\"projectAlias\", \"class\":\"tac\"}			        	\r\n");
      out.write("			        	, {\"data\":\"regUserName\",\"class\":\"tac\"}\r\n");
      out.write("			        	, {\"data\":\"regDatetime2\",\"class\":\"tac\"}\r\n");
      out.write("			        	//, {\"class\":\"ditailStyle tac\"}\r\n");
      out.write("			]\r\n");
      out.write("			,\"columnDefs\":[\r\n");
      out.write("				{\"defaultContent\" : \"\", targets:\"_all\" }\r\n");
      out.write("				//, {\"targets\":[0], \"render\": function(data,type,full){\r\n");
      out.write("				//	return \"<a href='#' onclick='moveDetailPage(\\\"\"+full.projectId+\"\\\")'>\" + full.projectName + \"</a>\";\r\n");
      out.write("				//	}	\r\n");
      out.write("				//}\r\n");
      out.write("// 				, {\"targets\":[1], \"render\": function(data,type,full){\r\n");
      out.write("// 					return \"<a href='#' onclick='moveDetailPage(\\\"\"+full.reqProjectSeq+\"\\\")'>\" + full.projectAlias + \"</a>\";\r\n");
      out.write("// 					}	\r\n");
      out.write("// 				}\r\n");
      out.write("				//, {\"targets\":[4], \"render\": function(data,type,full){\r\n");
      out.write("				//	return \"<button type='button' class='btn btn-grey_01' onclick='moveDetailPage(\\\"\"+full.projectId+\"\\\")' ><i class='fa fa-search'></i></button>\";\r\n");
      out.write("				//	}	\r\n");
      out.write("				//}\r\n");
      out.write("			]\r\n");
      out.write("			,\"order\": [[3,\"desc\"]]\r\n");
      out.write("			,\"lengthMenu\": [12]\r\n");
      out.write("			,\"language\": { \r\n");
      out.write("				\"zeroRecords\":\"\" \r\n");
      out.write("				, \"processing\":\"\"  \r\n");
      out.write("			}\r\n");
      out.write("			,\"sDom\":'<\"top\"><\"bottom\"ip>'\r\n");
      out.write("		});\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function moveDetailPage(reqProjectSeq){\r\n");
      out.write("		location.href = \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wasPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/req/project/projectView.do?reqProjectSeq=\"+reqProjectSeq;\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function setCardList(jsonData){\r\n");
      out.write("		var Html = \"\";\r\n");
      out.write("		\r\n");
      out.write("		$(\"#cardList > div\").remove();\r\n");
      out.write("\r\n");
      out.write("		var k = 1;\r\n");
      out.write("		\r\n");
      out.write("		for(var i=0; i<jsonData.data.length; i++){\r\n");
      out.write("			var projectAlias = 	jsonData.data[i][\"projectAlias\"];\r\n");
      out.write("			var customerName = jsonData.data[i][\"customerName\"];\r\n");
      out.write("			var deptName = jsonData.data[i][\"deptName\"];\r\n");
      out.write("			var regUserName = jsonData.data[i][\"regUserName\"];\r\n");
      out.write("			var regDatetime = jsonData.data[i][\"regDatetime2\"];\r\n");
      out.write("			var reqProjectSeq = jsonData.data[i][\"reqProjectSeq\"];\r\n");
      out.write("			var statusFlag = jsonData.data[i][\"statusFlag\"];\r\n");
      out.write("			var srApprovalStepHisCount = jsonData.data[i][\"srApprovalStepHisCount\"];\r\n");
      out.write("			\r\n");
      out.write("			if(k%5==0){\r\n");
      out.write("				k = 1;\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			if(i%4==0){\r\n");
      out.write("			//	Html += \"<div class='card_list_row'>\";\r\n");
      out.write("				Html += 	\"<div class='col-md-3 card_list_p color0\"+k+\"'>\";\r\n");
      out.write("			}else{\r\n");
      out.write("				Html += 	\"<div class='col-md-3 card_list_p color0\"+k+\"'>\";\r\n");
      out.write("			}\r\n");
      out.write("			\r\n");
      out.write("			Html +=			\"<a href='");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wasPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/req/project/projectView.do?reqProjectSeq=\"+reqProjectSeq+\"'>\";\r\n");
      out.write("	//		Html +=				\"<span class='basic_info'>\";\r\n");
      out.write("	\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("            if(statusFlag =='01'){\r\n");
      out.write("    			Html +=		      \"<li><span class='process_write mr10'>작성중</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='02' && srApprovalStepHisCount > 0){   \r\n");
      out.write("    			Html +=			  \"<li><span class='process_ing mr10'>진행중-변경</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='02' && srApprovalStepHisCount == 0){   \r\n");
      out.write("            	Html +=			  \"<li><span class='process_ing mr10'>진행중</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='03'){\r\n");
      out.write("            	Html +=			  \"<li><span class='process_re mr10'>반려</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='04'){\r\n");
      out.write("            	Html +=			  \"<li><span class='process_fix mr10'>처리완료</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='06'){\r\n");
      out.write("            	Html +=			  \"<li><span class='process_cancel mr10'>상신취소</span></li>\";	\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write("\r\n");
      out.write("			Html +=					\"<li class='project_name'>\"+projectAlias+\"</li>\";\r\n");
      out.write("			\r\n");
      out.write("\r\n");
      out.write("  /*           if(statusFlag =='01'){\r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-pencil f30 fc_blue'></i></li>\";    \r\n");
      out.write("    			Html +=				\"<li class='db center f14 fb tac pt10'>작성중</li>\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='02' && srApprovalStepHisCount > 0){   \r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-hourglass-2 f30 fc_green'></i></li>\";  \r\n");
      out.write("    			Html +=				\"<li class='db center f14 fb tac pt10'>진행중(변경)</li>\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='02' && srApprovalStepHisCount == 0){   \r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-hourglass-2 f30 fc_green'></i></li>\";  \r\n");
      out.write("			    Html +=				\"<li class='db center f14 fb tac pt10'>진행중</li>\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='03'){\r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-reply f30 fc_red'></i></li>\";     \r\n");
      out.write("    			Html +=				\"<li class='db center f14 fb tac pt10'>반려</li>\";\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='04'){\r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-check-square-o f30 fc_violet'></i></li>\";   \r\n");
      out.write("    			Html +=				\"<li class='db center f14 fb tac pt10'>처리완료</li>\";\r\n");
      out.write("\r\n");
      out.write("            }else if(statusFlag =='06'){\r\n");
      out.write("    			Html +=				\"<li class='code_c'><i class='fa fa-reply f30 fc-khaki'></i></li>\";   \r\n");
      out.write("    			Html +=				\"<li class='db center f14 fb tac pt10'>상신 취소</li>\";\r\n");
      out.write("\r\n");
      out.write("            }\r\n");
      out.write(" */\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("            \r\n");
      out.write("			                        \r\n");
      out.write("	//		Html +=				\"</span>\";\r\n");
      out.write("			Html +=				\"<li class='name mt20'>\"+customerName+\"/ \"+deptName + \" <span>(\"+regUserName+\")</span></li>\";\r\n");
      out.write("	//		Html +=				\"<li class='name'>\"+deptName +\" <span>(\"+regUserName+\")</span></li>\";\r\n");
      out.write("			regDatetime = regDatetime.replace(/\\//g, \"-\");		\r\n");
      out.write("			Html +=				\"<li><span class='date'><span class='date_text'>\"+regDatetime + \"</span></span></li>\";\r\n");
      out.write("			Html +=			\"</a>\";\r\n");
      out.write("//			Html +=			\"<span class='color_btm'></span>\";\r\n");
      out.write("			Html += 	\"</div>\";\r\n");
      out.write("			\r\n");
      out.write("			if(i%4==0){\r\n");
      out.write("		//		Html += \"</div>\";\r\n");
      out.write("			}\r\n");
      out.write("		  \r\n");
      out.write("			k++;\r\n");
      out.write("			\r\n");
      out.write("		}\r\n");
      out.write("		$(\"#cardList\").append(Html);\r\n");
      out.write("		\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	function moveInsertPage(){\r\n");
      out.write("		\r\n");
      out.write("		if(\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${isPM}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("\" == \"true\"){\r\n");
      out.write("			location.href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${wasPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/req/project/projectInsert.do\";\r\n");
      out.write("		}else{\r\n");
      out.write("			alertBox3(\"프로젝트 신청권한이 없습니다.\");\r\n");
      out.write("		}	\r\n");
      out.write("	}\r\n");
      out.write("	\r\n");
      out.write("	\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		 App.init();\r\n");
      out.write("		 gridList();\r\n");
      out.write("		 \r\n");
      out.write("		// select box text 설정\r\n");
      out.write("		$(\".search-sel\").change(function() {\r\n");
      out.write("			$(this).siblings(\".selectText\").text($(this).children('option:selected').text());\r\n");
      out.write("		});\r\n");
      out.write("		\r\n");
      out.write("		//메뉴활성화\r\n");
      out.write("		$(\"#reqStatus\").addClass(\"active\");\r\n");
      out.write("	 	$(\"#projectRequestList\").addClass(\"active\");\r\n");
      out.write("			\r\n");
      out.write("	});	\r\n");
      out.write("	\r\n");
      out.write("	</script>\r\n");
      out.write("</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_sec_005fauthorize_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f0 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f0.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(7,0) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f0.setAccess("isAuthenticated()");
      int _jspx_eval_sec_005fauthorize_005f0 = _jspx_th_sec_005fauthorize_005f0.doStartTag();
      if (_jspx_eval_sec_005fauthorize_005f0 != javax.servlet.jsp.tagext.Tag.SKIP_BODY) {
        out.write('\r');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_sec_005fauthentication_005f0(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
        out.write('	');
        if (_jspx_meth_sec_005fauthentication_005f1(_jspx_th_sec_005fauthorize_005f0, _jspx_page_context))
          return true;
        out.write('\r');
        out.write('\n');
      }
      if (_jspx_th_sec_005fauthorize_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005faccess.reuse(_jspx_th_sec_005fauthorize_005f0);
      _jspx_th_sec_005fauthorize_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f0(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f0 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f0_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f0.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f0.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(8,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setVar("userId");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(8,1) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f0.setProperty("principal.username");
      int _jspx_eval_sec_005fauthentication_005f0 = _jspx_th_sec_005fauthentication_005f0.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f0);
      _jspx_th_sec_005fauthentication_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f0, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthentication_005f1(javax.servlet.jsp.tagext.JspTag _jspx_th_sec_005fauthorize_005f0, javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authentication
    org.springframework.security.taglibs.authz.AuthenticationTag _jspx_th_sec_005fauthentication_005f1 = (org.springframework.security.taglibs.authz.AuthenticationTag) _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.get(org.springframework.security.taglibs.authz.AuthenticationTag.class);
    boolean _jspx_th_sec_005fauthentication_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthentication_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthentication_005f1.setParent((javax.servlet.jsp.tagext.Tag) _jspx_th_sec_005fauthorize_005f0);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(9,1) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setVar("userName");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(9,1) name = property type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthentication_005f1.setProperty("principal.nickname");
      int _jspx_eval_sec_005fauthentication_005f1 = _jspx_th_sec_005fauthentication_005f1.doStartTag();
      if (_jspx_th_sec_005fauthentication_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthentication_0026_005fvar_005fproperty_005fnobody.reuse(_jspx_th_sec_005fauthentication_005f1);
      _jspx_th_sec_005fauthentication_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthentication_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthentication_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_sec_005fauthorize_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  sec:authorize
    org.springframework.security.taglibs.authz.JspAuthorizeTag _jspx_th_sec_005fauthorize_005f1 = (org.springframework.security.taglibs.authz.JspAuthorizeTag) _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fvar_005faccess_005fnobody.get(org.springframework.security.taglibs.authz.JspAuthorizeTag.class);
    boolean _jspx_th_sec_005fauthorize_005f1_reused = false;
    try {
      _jspx_th_sec_005fauthorize_005f1.setPageContext(_jspx_page_context);
      _jspx_th_sec_005fauthorize_005f1.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(11,0) name = var type = java.lang.String reqTime = false required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setVar("isPM");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(11,0) name = access type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_sec_005fauthorize_005f1.setAccess("hasRole('ROLE_CUSTOM_PM')");
      int _jspx_eval_sec_005fauthorize_005f1 = _jspx_th_sec_005fauthorize_005f1.doStartTag();
      if (_jspx_th_sec_005fauthorize_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
        return true;
      }
      _005fjspx_005ftagPool_005fsec_005fauthorize_0026_005fvar_005faccess_005fnobody.reuse(_jspx_th_sec_005fauthorize_005f1);
      _jspx_th_sec_005fauthorize_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_sec_005fauthorize_005f1, _jsp_getInstanceManager(), _jspx_th_sec_005fauthorize_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(21,1) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../../include/import.jsp");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(21,1) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(30,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../../include/header.jsp");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(30,2) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(34,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("../../include/sidebar.jsp");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(34,2) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f3 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f3_reused = false;
    try {
      _jspx_th_c_005fimport_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f3.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(74,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f3.setUrl("../../include/footer.jsp");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(74,3) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f3.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f3 = _jspx_th_c_005fimport_005f3.doStartTag();
        if (_jspx_th_c_005fimport_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f3);
      _jspx_th_c_005fimport_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f4 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f4_reused = false;
    try {
      _jspx_th_c_005fimport_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f4.setParent(null);
      // /WEB-INF/views/mbr/req/project/projectList.jsp(83,0) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f4.setUrl("../../include/script.jsp");
      // /WEB-INF/views/mbr/req/project/projectList.jsp(83,0) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f4.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f4 = _jspx_th_c_005fimport_005f4.doStartTag();
        if (_jspx_th_c_005fimport_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f4);
      _jspx_th_c_005fimport_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f4_reused);
    }
    return false;
  }
}
