stages:
  - build
  - deploy

build-job:
  stage: build
  script:
    - echo "🔧 Building the project on 101 server"
    - ssh -o StrictHostKeyChecking=no root@192.168.100.101 "
        cd /app/git/k-cloud-20250113-dev/iVuCenter_Cloud_Was &&
        git pull origin main &&
        /usr/local/maven/bin/mvn clean package -DskipTests
      "
  only:
    - main

deploy-job:
  stage: deploy
  script:
    - echo "🚀 Deploying to Tomcat on 101 server"
    - ssh -o StrictHostKeyChecking=no root@192.168.100.101 "
        rm -rf /home/3hs/server/tomcat/tomcat9/kcloud/webapps/ROOT &&
        mv /app/git/k-cloud-20250113-dev/iVuCenter_Cloud_Was/target/*.war /home/3hs/server/tomcat/tomcat9/kcloud/webapps/ROOT.war &&
        sh /home/3hs/server/tomcat/tomcat9/kcloud/bin/shutdown.sh || true &&
        sleep 5 &&
        sh /home/3hs/server/tomcat/tomcat9/kcloud/bin/startup.sh
      "
  only:
    - main

