/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.56
 * Generated at: 2025-03-07 02:23:15 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views.mng.monitoring.event;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class realtimeEventList_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(4);
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/fn.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1709100854747L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153352682000L));
    _jspx_dependants.put("jar:file:/D:/workspace/k-cloud-20250113-dev/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/iVuCenter_Cloud_Was/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153352682000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private org.apache.jasper.runtime.TagHandlerPool _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody = org.apache.jasper.runtime.TagHandlerPool.getTagHandlerPool(getServletConfig());
  }

  public void _jspDestroy() {
    _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.release();
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSP들은 오직 GET, POST 또는 HEAD 메소드만을 허용합니다. Jasper는 OPTIONS 메소드 또한 허용합니다.");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("\r\n");
      out.write("<html lang=\"ko\">\r\n");
      out.write("	<head>\r\n");
      out.write("		<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("		<meta http-equiv=\"X-UA-Compatible\" >\r\n");
      out.write("		<meta content=\"width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=no\" name=\"viewport\" />\r\n");
      out.write("		<meta content=\"\" name=\"description\" />\r\n");
      out.write("		<meta content=\"\" name=\"author\" />\r\n");
      out.write("		<link rel=\"stylesheet\" type=\"text/css\" href=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apachePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/css/ui.jqgrid.css\" />\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f0(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<title>KEPCO Cloud Service Platform</title>\r\n");
      out.write("	</head>\r\n");
      out.write("\r\n");
      out.write("	<body>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("		<!-- begin #page-container -->\r\n");
      out.write("		<div id=\"page-container\" class=\"fade page-container page-header-fixed page-sidebar-fixed page-with-footer\">\r\n");
      out.write("			<!-- begin #header -->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fimport_005f1(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<!-- end #header -->\r\n");
      out.write("\r\n");
      out.write("			<!-- begin #sidebar -->\r\n");
      out.write("			");
      if (_jspx_meth_c_005fimport_005f2(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("			<!-- end #sidebar -->\r\n");
      out.write("\r\n");
      out.write("			<!-- begin #content -->\r\n");
      out.write("			<div id=\"content\" class=\"content\">\r\n");
      out.write("				<!-- begin header -->\r\n");
      out.write("\r\n");
      out.write("				<div class=\"page_header mb30\">\r\n");
      out.write("					<h1>이벤트 발생 현황</h1>\r\n");
      out.write("					<div class=\"pageNav\">\r\n");
      out.write("						<a href=\"#\" class=\"home\"><i></i></a><a href=\"#\">모니터링</a><a href=\"#\" class=\"on\">이벤트 발생 현황</a>\r\n");
      out.write("					</div>\r\n");
      out.write("				</div>\r\n");
      out.write("				<!-- end header -->\r\n");
      out.write("\r\n");
      out.write("				<!-- begin #content page-body -->\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_source\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_firstoccurtime\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_identifier\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_tally\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_severityName\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_alertgroup\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_agent\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_alertkey\"/>\r\n");
      out.write("                    <input type=\"hidden\" id=\"h_eventAt\"/>\r\n");
      out.write("\r\n");
      out.write("				<div class=\"mb50\">\r\n");
      out.write("					<!-- search begin -->\r\n");
      out.write("					<div class=\"page_searchBox\">\r\n");
      out.write("						<div class=\"searchArea\">\r\n");
      out.write("							<div class=\"selectBox\">\r\n");
      out.write("								<label class=\"selectText\" for=\"searchKind\">전체</label>\r\n");
      out.write("								<select class=\"search-sel width-150\" id=\"searchKind\">\r\n");
      out.write("									<option value=\"searchAll\">전체</option>\r\n");
      out.write("									<option value=\"hostname_alias\">서버명</option>\r\n");
      out.write("									<option value=\"hostname\">호스트명</option>\r\n");
      out.write("									<option value=\"ip\">IP</option>\r\n");
      out.write("								</select>\r\n");
      out.write("							</div>\r\n");
      out.write("								<input type=\"text\" placeholder=\"검색어를 입력하세요\" id=\"keyword\" onkeypress=\"if(event.keyCode==13)loadData();\" class=\"width-600 ml5\">\r\n");
      out.write("								<a type=\"button\" class=\"bton-s bton_blue\" onclick=\"loadData()\"> <i class=\"fa fa-search\"></i>  검색</a>\r\n");
      out.write("						</div>\r\n");
      out.write("					</div>\r\n");
      out.write("\r\n");
      out.write("				<!-- search end -->\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"wrap\">\r\n");
      out.write("                        <div class=\"mb30\">\r\n");
      out.write("                            <div class=\"mt-3 col-md-12\">\r\n");
      out.write("                                <ul class=\"event-status-list-wrap\" id=\"eventAt\">\r\n");
      out.write("                                    <li class=\"event-status-05\"><a onclick=\"eventAtSet('critical')\"><span>심각(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventCnt.criticalCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></a></li>\r\n");
      out.write("                                    <li class=\"event-status-02\"><a onclick=\"eventAtSet('warning')\"><span>경고(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventCnt.warningCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></a></li>\r\n");
      out.write("                                    <li class=\"event-status-03\"><a onclick=\"eventAtSet('info')\"><span>주의(");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${eventCnt.infoCnt}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write(")</span></a></li>\r\n");
      out.write("                                </ul>\r\n");
      out.write("                                <div class=\"overflow-wrapper\">\r\n");
      out.write("                                    <table id=\"list\" class=\"tableV\">\r\n");
      out.write("                                        <colgroup>\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"*\" />\r\n");
      out.write("                                            <col width=\"15%\" />\r\n");
      out.write("                                            <col width=\"70px\" />\r\n");
      out.write("                                        </colgroup>\r\n");
      out.write("                                        <thead>\r\n");
      out.write("                                            <tr>\r\n");
      out.write("                                                <th>망구분</th>\r\n");
      out.write("                                                <th>프로젝트</th>\r\n");
      out.write("                                                <th>서버명</th>\r\n");
      out.write("                                                <th>발생일시</th>\r\n");
      out.write("                                                <th>소스</th>\r\n");
      out.write("                                                <th>호스트명</th>\r\n");
      out.write("                                                <th>등급</th>\r\n");
      out.write("                                                <th>이벤트내용</th>\r\n");
      out.write("                                                <th>확인</th>\r\n");
      out.write("                                            </tr>\r\n");
      out.write("                                        </thead>\r\n");
      out.write("                                    </table>\r\n");
      out.write("                                </div>\r\n");
      out.write("                            </div>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </div>\r\n");
      out.write("				<!---- end page body---->\r\n");
      out.write("                <!-- 모달 시작 -->\r\n");
      out.write("				<div class=\"modal fade\" id=\"eventDetailView\" tabindex=\"-1\" role=\"dialog\" aria-hidden=\"true\">\r\n");
      out.write("				    <div class=\"modal-dialog modal-dialog-centered\" role=\"document\">\r\n");
      out.write("				        <div class=\"modal-content width-700\">\r\n");
      out.write("				            <div class=\"modal-header\">\r\n");
      out.write("				                <h5 class=\"modal-title\">상세</h5>\r\n");
      out.write("				                <button type=\"button\" class=\"btn btn-close btn-close-black\" data-dismiss=\"modal\" aria-label=\"Close\"></button>\r\n");
      out.write("				            </div>\r\n");
      out.write("				            <div class=\"modal-body \">\r\n");
      out.write("				                <div class=\"tab\">\r\n");
      out.write("				                    <ul class=\"nav nav-tabs\" role=\"tablist\">\r\n");
      out.write("				                        <li class=\"nav-item\"><a class=\"nav-link active\" href=\"#tab-1\" data-toggle=\"tab\" role=\"tab\">자원정보</a></li>\r\n");
      out.write("				                        <li class=\"nav-item\"><a class=\"nav-link\" href=\"#tab-2\" data-toggle=\"tab\" role=\"tab\">이벤트</a></li>\r\n");
      out.write("				                    </ul>\r\n");
      out.write("				                    <div class=\"tab-content active\">\r\n");
      out.write("				                        <div class=\"tab-pane active\" id=\"tab-1\" role=\"tabpanel\">\r\n");
      out.write("				                            <table>\r\n");
      out.write("											<colgroup>\r\n");
      out.write("												<col width=\"140px\"/>\r\n");
      out.write("												<col width=\"*\"/>\r\n");
      out.write("												<col width=\"140px\"/>\r\n");
      out.write("												<col width=\"*\"/>\r\n");
      out.write("											</colgroup>\r\n");
      out.write("				                                <tbody>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>망구분</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"zoneDisplayName\" readonly></td>\r\n");
      out.write("				                                        <th>프로젝트</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"projectName\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>소스</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"source\" readonly></td>\r\n");
      out.write("				                                        <th>IP 주소</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"ip\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>호스트명</th>\r\n");
      out.write("				                                        <td colspan=\"3\"><input type=\"text\" class=\"form-control\" id=\"hostname\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>모델명</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"model\" readonly></td>\r\n");
      out.write("				                                        <th>OS</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"osname\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>OS 버전</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"ostype\" readonly></td>\r\n");
      out.write("				                                        <th>CPU Core 수</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"corecnt\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>메모리 총량</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"pmemgb\" readonly></td>\r\n");
      out.write("				                                        <th>내장 Disk 총량</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"disktotalgb\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                </tbody>\r\n");
      out.write("				                            </table>\r\n");
      out.write("				                        </div>\r\n");
      out.write("				                        <div class=\"tab-pane\" id=\"tab-2\" role=\"tabpanel\">\r\n");
      out.write("				                            <table>\r\n");
      out.write("											<colgroup>\r\n");
      out.write("												<col width=\"140px\"/>\r\n");
      out.write("												<col width=\"*\"/>\r\n");
      out.write("												<col width=\"140px\"/>\r\n");
      out.write("												<col width=\"*\"/>\r\n");
      out.write("											</colgroup>\r\n");
      out.write("				                                <tbody>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>발생일시</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"firstoccurtime\" readonly></td>\r\n");
      out.write("				                                        <th>심각도</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"severityName\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>메세지</th>\r\n");
      out.write("				                                        <td colspan=\"3\"><input type=\"text\" class=\"form-control\" id=\"message\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>경고그룹</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"alertgroup\" readonly></td>\r\n");
      out.write("				                                        <th>경고키</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"alertkey\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>관리 장비수</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"tally\" readonly></td>\r\n");
      out.write("				                                        <th>에이전트</th>\r\n");
      out.write("				                                        <td><input type=\"text\" class=\"form-control\" id=\"agent\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                    <tr>\r\n");
      out.write("				                                        <th>이벤트 내용</th>\r\n");
      out.write("				                                        <td colspan=\"3\"><input type=\"text\" class=\"form-control\" id=\"identifier\" readonly></td>\r\n");
      out.write("				                                    </tr>\r\n");
      out.write("				                                </tbody>\r\n");
      out.write("				                            </table>\r\n");
      out.write("				                        </div>\r\n");
      out.write("				                    </div>\r\n");
      out.write("				                </div>\r\n");
      out.write("				            </div>\r\n");
      out.write("				            <div class=\"modal-footer btn-wrap\">\r\n");
      out.write("				                <button class=\"btn btn-del wid-75\" onclick=\"loadDelete()\">삭제</button>\r\n");
      out.write("				                <!-- <button class=\"btn btn-primary wid-75\">장애등록</button> -->\r\n");
      out.write("				                <button class=\"btn btn-outline-primary wid-75\" data-dismiss=\"modal\" aria-label=\"close\">닫기</button>\r\n");
      out.write("				            </div>\r\n");
      out.write("				        </div>\r\n");
      out.write("				    </div>\r\n");
      out.write("                <!-- 모달 끝 -->\r\n");
      out.write("				</div>\r\n");
      out.write("				<div class=\"clear\"></div>\r\n");
      out.write("				<!-- begin #footer -->\r\n");
      out.write("					");
      if (_jspx_meth_c_005fimport_005f3(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("				<!-- end #footer -->\r\n");
      out.write("			</div>\r\n");
      out.write("			<!-- end #content -->\r\n");
      out.write("\r\n");
      out.write("		</div>\r\n");
      out.write("		<!-- end page container -->\r\n");
      out.write("		");
      if (_jspx_meth_c_005fimport_005f4(_jspx_page_context))
        return;
      out.write("\r\n");
      out.write("		<script type=\"text/javascript\" src=\"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${apachePath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/resources/js/plugins/jquery.jqGrid.js\"></script>\r\n");
      out.write("		<script type=\"text/javascript\">\r\n");
      out.write("		function eventAtSet(at){\r\n");
      out.write("		    $(\"#h_eventAt\").val(at);\r\n");
      out.write("		    loadData();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	    function loadData(){\r\n");
      out.write("	        $(\"#list\").DataTable({\r\n");
      out.write("	            \"processing\": true,\r\n");
      out.write("	            \"autoWidth\": true,\r\n");
      out.write("	            \"serverSide\": true,\r\n");
      out.write("	            \"ordering\": false,\r\n");
      out.write("	            \"destroy\": true,\r\n");
      out.write("	            \"searching\": false,\r\n");
      out.write("	            \"lengthChange\": false,\r\n");
      out.write("	            \"responsive\": true,\r\n");
      out.write("	            \"ajax\": {\r\n");
      out.write("	                \"url\": \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/monitoring/event/mbrList\",\r\n");
      out.write("	                \"type\": \"GET\",\r\n");
      out.write("	                \"data\": function (d) {\r\n");
      out.write("	                    d.searchKind = $(\"#searchKind option:selected\").val();\r\n");
      out.write("	                    d.keyword = $(\"#keyword\").val();\r\n");
      out.write("	                    d.eventAt = $(\"#h_eventAt\").val();\r\n");
      out.write("	                },\r\n");
      out.write("	                \"complete\": function(obj, status){\r\n");
      out.write("	                    if(status === 'success'){\r\n");
      out.write("	                        afterLoad(obj.responseJSON);\r\n");
      out.write("	                    }\r\n");
      out.write("	                }\r\n");
      out.write("	            },\r\n");
      out.write("	            \"columns\": [\r\n");
      out.write("	                {\"data\": \"zoneDisplayName\"},\r\n");
      out.write("	                {\"data\": \"projectName\"},\r\n");
      out.write("	                {\"data\": \"hostnameAlias\"},\r\n");
      out.write("	                {\"data\": \"firstoccurtime\"},\r\n");
      out.write("	                {\"data\": \"source\"},\r\n");
      out.write("	                {\"data\": \"hostname\"},\r\n");
      out.write("	                {\"data\": \"severityName\"},\r\n");
      out.write("	                {\"data\": \"identifier\"},\r\n");
      out.write("	                {}\r\n");
      out.write("	            ],\r\n");
      out.write("	            \"createdRow\": function(row, data, dataIndex) {\r\n");
      out.write("	                $(row).attr(\"id\", \"id_\" + dataIndex);\r\n");
      out.write("	            },\r\n");
      out.write("	            \"columnDefs\":[\r\n");
      out.write("	                {\"defaultContent\" : \"\", targets:\"_all\" },\r\n");
      out.write("	                {\"targets\":[0], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.zoneDisplayName;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[1], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.projectName;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[2], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.hostnameAlias;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[3], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.firstoccurtime;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[4], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.source;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[5], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.hostname;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[6], \"render\": function(data,type,full){\r\n");
      out.write("	                    return full.severityName;\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[7], \"render\": function(data,type,full){\r\n");
      out.write("	                    return \"<div style='white-space: nowrap; overflow: hidden; text-overflow: ellipsis; max-width: 200px;' title='\" + full.identifier + \"'>\" + full.identifier + \"</div>\";\r\n");
      out.write("	                }},\r\n");
      out.write("	                {\"targets\":[8], \"orderable\" : false, \"render\" : function(data,type,full){\r\n");
      out.write("	                    return \"<a class='cbton bton_lblue' onclick='popupDetail(\\\"\"+full.zoneDisplayName+\"\\\",\\\"\"+full.projectName+\"\\\",\\\"\"+full.source+\"\\\",\\\"\"+full.hostname+\"\\\",\\\"\"+full.ip+\"\\\",\\\"\"+full.model+\"\\\",\\\"\"+full.osname+\"\\\",\\\"\"+full.ostype+\"\\\",\\\"\"+full.corecnt+\"\\\",\\\"\"+full.pmemgb+\"\\\",\\\"\"+full.disktotalgb+\"\\\",\\\"\"+full.firstoccurtime+\"\\\",\\\"\"+full.identifier+\"\\\",\\\"\"+full.tally+\"\\\",\\\"\"+full.severityName+\"\\\",\\\"\"+full.alertgroup+\"\\\",\\\"\"+full.agent+\"\\\",\\\"\"+full.alertkey+\"\\\")' ><i class='fa fa-search'></i></a>\";\r\n");
      out.write("	                }}\r\n");
      out.write("	            ],\r\n");
      out.write("	            \"order\": [[3, \"desc\"]],\r\n");
      out.write("	            \"lengthMenu\": [[10, 15], [10, 15]],\r\n");
      out.write("	            \"language\": {\r\n");
      out.write("	                \"zeroRecords\": \"<p align='center'>검색결과가 없습니다.</p>\",\r\n");
      out.write("	                \"processing\": \"<div style='background-color:#fff;padding-top:50px;padding-bottom:50px;'><p align='center' style='color:#bbb; font-weight:bold;'>검색중입니다.</p></div>\"\r\n");
      out.write("	            },\r\n");
      out.write("	            \"sDom\": '<\"top\">rt<\"bottom\"pi>'\r\n");
      out.write("	        });\r\n");
      out.write("	    }\r\n");
      out.write("\r\n");
      out.write("		function popupDetail(zoneDisplayName, projectName, source, hostname, ip, model, osname, ostype, corecnt, pmemgb, disktotalgb, firstoccurtime, identifier, tally, severityName, alertgroup, agent, alertkey){\r\n");
      out.write("			$(\"#h_zoneDisplayName\").val(zoneDisplayName);\r\n");
      out.write("			$(\"#h_projectName\").val(projectName);\r\n");
      out.write("			$(\"#h_source\").val(source);\r\n");
      out.write("			$(\"#h_hostname\").val(hostname);\r\n");
      out.write("			$(\"#h_ip\").val(ip);\r\n");
      out.write("			$(\"#h_model\").val(model);\r\n");
      out.write("			$(\"#h_osname\").val(osname);\r\n");
      out.write("			$(\"#h_ostype\").val(ostype);\r\n");
      out.write("			$(\"#h_corecnt\").val(corecnt);\r\n");
      out.write("			$(\"#h_pmemgb\").val(pmemgb);\r\n");
      out.write("			$(\"#h_disktotalgb\").val(disktotalgb);\r\n");
      out.write("			$(\"#h_firstoccurtime\").val(firstoccurtime);\r\n");
      out.write("			$(\"#h_identifier\").val(identifier);\r\n");
      out.write("			$(\"#h_tally\").val(tally);\r\n");
      out.write("			$(\"#h_severityName\").val(severityName);\r\n");
      out.write("			$(\"#h_alertgroup\").val(alertgroup);\r\n");
      out.write("			$(\"#h_agent\").val(agent);\r\n");
      out.write("			$(\"#h_alertkey\").val(alertkey);\r\n");
      out.write("			$(\"#eventDetailView\").modal('show');\r\n");
      out.write("			deviceDetail();\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function deviceDetail(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/monitoring/event/resource-info/hostname2\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				data : {\r\n");
      out.write("					\"identifier\" : $(\"#h_identifier\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					setData(data);\r\n");
      out.write("				},\r\n");
      out.write("				error : function(request, status, error) {\r\n");
      out.write("					if(request.status == '200'){\r\n");
      out.write("						alertBox(\"접속이 만료되었습니다.\", logout);\r\n");
      out.write("					}else{\r\n");
      out.write("						alertBox3(\"code:\" + request.status + \"\\n\" + \"error:\" + error);\r\n");
      out.write("					}\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function setData(data) {\r\n");
      out.write("		    delete data.length;\r\n");
      out.write("		    $.each(data, function(key, val) {\r\n");
      out.write("		        if ($(\"#\" + key).is(\"select\")) {\r\n");
      out.write("		            $(\"#\" + key + \" option\").each(function() {\r\n");
      out.write("		                if ($(this).val() == val) {\r\n");
      out.write("		                    $(this).prop(\"selected\", true);\r\n");
      out.write("		                }\r\n");
      out.write("		            });\r\n");
      out.write("		        } else {\r\n");
      out.write("		            $(\"#\" + key).val(val);\r\n");
      out.write("		        }\r\n");
      out.write("		    });\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function loadDelete(){\r\n");
      out.write("			$.ajax({\r\n");
      out.write("				url : \"");
      out.write((java.lang.String) org.apache.jasper.runtime.PageContextImpl.proprietaryEvaluate("${contextPath}", java.lang.String.class, (javax.servlet.jsp.PageContext)_jspx_page_context, null));
      out.write("/mbr/monitoring/event/delete\",\r\n");
      out.write("				dataType : \"JSON\",\r\n");
      out.write("				type : \"POST\",\r\n");
      out.write("				data : {\r\n");
      out.write("					  \"identifier\" : $(\"#identifier\").val()\r\n");
      out.write("				},\r\n");
      out.write("				success : function(data) {\r\n");
      out.write("					if(data==1){\r\n");
      out.write("						alertBox(\"삭제되었습니다.\", function() {\r\n");
      out.write("						location.reload();\r\n");
      out.write("						});\r\n");
      out.write("					} else {\r\n");
      out.write("						alertBox3(\"삭제 실패\");\r\n");
      out.write("					}\r\n");
      out.write("				},\r\n");
      out.write("				error : function(request, status, error) {\r\n");
      out.write("					errorBox(\"code:\" + request.status + \"\\n\" + \"error:\" + error);\r\n");
      out.write("				}\r\n");
      out.write("			});\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("		function afterLoad(obj) {\r\n");
      out.write("		    var listData = $(\"#list\").DataTable();\r\n");
      out.write("		    var rowData = listData.rows().data();\r\n");
      out.write("		    for (var i = 0; i < rowData.length; i++) {\r\n");
      out.write("		        var severity = listData.row(i).data().severity;\r\n");
      out.write("		        var rowid = listData.row(i).index();\r\n");
      out.write("		        switch (severity) {\r\n");
      out.write("		            case 'critical':\r\n");
      out.write("		                $(\"#id_\" + rowid).addClass('event-status-05');\r\n");
      out.write("		                break;\r\n");
      out.write("		            case 'info':\r\n");
      out.write("		                $(\"#id_\" + rowid).addClass('event-status-03');\r\n");
      out.write("		                break;\r\n");
      out.write("		            case 'warning':\r\n");
      out.write("		                $(\"#id_\" + rowid).addClass('event-status-02');\r\n");
      out.write("		                break;\r\n");
      out.write("		            default:\r\n");
      out.write("		                break;\r\n");
      out.write("		        }\r\n");
      out.write("		    }\r\n");
      out.write("		}\r\n");
      out.write("\r\n");
      out.write("	$(document).ready(function() {\r\n");
      out.write("		App.init();\r\n");
      out.write("		loadData();\r\n");
      out.write("\r\n");
      out.write("		//메뉴활성화\r\n");
      out.write("		$(\"#monitoring\").addClass(\"active\");\r\n");
      out.write("		$(\"#eventList\").addClass(\"active\");\r\n");
      out.write("\r\n");
      out.write("// 		$(\"#searchKind\").val(\"searchAll\");\r\n");
      out.write("	});\r\n");
      out.write("		</script>\r\n");
      out.write("\r\n");
      out.write("	</body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }

  private boolean _jspx_meth_c_005fimport_005f0(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f0 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f0_reused = false;
    try {
      _jspx_th_c_005fimport_005f0.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f0.setParent(null);
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(16,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setUrl("../../include/import.jsp");
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(16,2) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f0.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f0 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f0 = _jspx_th_c_005fimport_005f0.doStartTag();
        if (_jspx_th_c_005fimport_005f0.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f0[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f0.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f0.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f0);
      _jspx_th_c_005fimport_005f0_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f0, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f0_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f1(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f1 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f1_reused = false;
    try {
      _jspx_th_c_005fimport_005f1.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f1.setParent(null);
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(26,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setUrl("../../include/header.jsp");
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(26,3) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f1.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f1 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f1 = _jspx_th_c_005fimport_005f1.doStartTag();
        if (_jspx_th_c_005fimport_005f1.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f1[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f1.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f1.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f1);
      _jspx_th_c_005fimport_005f1_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f1, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f1_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f2(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f2 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f2_reused = false;
    try {
      _jspx_th_c_005fimport_005f2.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f2.setParent(null);
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(30,3) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setUrl("../../include/sidebar.jsp");
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(30,3) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f2.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f2 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f2 = _jspx_th_c_005fimport_005f2.doStartTag();
        if (_jspx_th_c_005fimport_005f2.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f2[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f2.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f2.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f2);
      _jspx_th_c_005fimport_005f2_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f2, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f2_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f3(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f3 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f3_reused = false;
    try {
      _jspx_th_c_005fimport_005f3.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f3.setParent(null);
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(230,5) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f3.setUrl("../../include/footer.jsp");
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(230,5) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f3.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f3 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f3 = _jspx_th_c_005fimport_005f3.doStartTag();
        if (_jspx_th_c_005fimport_005f3.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f3[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f3.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f3.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f3);
      _jspx_th_c_005fimport_005f3_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f3, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f3_reused);
    }
    return false;
  }

  private boolean _jspx_meth_c_005fimport_005f4(javax.servlet.jsp.PageContext _jspx_page_context)
          throws java.lang.Throwable {
    javax.servlet.jsp.PageContext pageContext = _jspx_page_context;
    javax.servlet.jsp.JspWriter out = _jspx_page_context.getOut();
    //  c:import
    org.apache.taglibs.standard.tag.rt.core.ImportTag _jspx_th_c_005fimport_005f4 = (org.apache.taglibs.standard.tag.rt.core.ImportTag) _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.get(org.apache.taglibs.standard.tag.rt.core.ImportTag.class);
    boolean _jspx_th_c_005fimport_005f4_reused = false;
    try {
      _jspx_th_c_005fimport_005f4.setPageContext(_jspx_page_context);
      _jspx_th_c_005fimport_005f4.setParent(null);
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(237,2) name = url type = null reqTime = true required = true fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f4.setUrl("../../include/script.jsp");
      // /WEB-INF/views/mng/monitoring/event/realtimeEventList.jsp(237,2) name = charEncoding type = null reqTime = true required = false fragment = false deferredValue = false expectedTypeName = null deferredMethod = false methodSignature = null
      _jspx_th_c_005fimport_005f4.setCharEncoding("UTF-8");
      int[] _jspx_push_body_count_c_005fimport_005f4 = new int[] { 0 };
      try {
        int _jspx_eval_c_005fimport_005f4 = _jspx_th_c_005fimport_005f4.doStartTag();
        if (_jspx_th_c_005fimport_005f4.doEndTag() == javax.servlet.jsp.tagext.Tag.SKIP_PAGE) {
          return true;
        }
      } catch (java.lang.Throwable _jspx_exception) {
        while (_jspx_push_body_count_c_005fimport_005f4[0]-- > 0)
          out = _jspx_page_context.popBody();
        _jspx_th_c_005fimport_005f4.doCatch(_jspx_exception);
      } finally {
        _jspx_th_c_005fimport_005f4.doFinally();
      }
      _005fjspx_005ftagPool_005fc_005fimport_0026_005furl_005fcharEncoding_005fnobody.reuse(_jspx_th_c_005fimport_005f4);
      _jspx_th_c_005fimport_005f4_reused = true;
    } finally {
      org.apache.jasper.runtime.JspRuntimeLibrary.releaseTag(_jspx_th_c_005fimport_005f4, _jsp_getInstanceManager(), _jspx_th_c_005fimport_005f4_reused);
    }
    return false;
  }
}
