package com.ivucenter.cloud.api.gitlab;

public enum GitlabType {
	TOKEN, PIPELINE, USER_LIST, PROPERTIES, RESULT, PROJECT, PIPELINE_LIST, PROJECT_LIST, PROJECT_MEMBER, USER, GROUP,
	GROUP_MEMBER, BRANCH, BRANCH_LIST, FILE, MERGE_REQUEST, MERGE_REQUEST_LIST, TAG, APPROVAL_RULE_LIST, APPROVAL_RULE,
	MERGE_REQUEST_APPROVE, JOB_LIST, ENVIRONMENT, CHECK_ENVIRONMENT, PROTECTED_ENVIRONMENT, CHECK_PROTECTED_ENVIRONMENT,
	CHECK_DEPLOYMENT, DEPLOYMENT_START, CHECK_MENUAL_STATUS ,MENUAL_STATUS_START
}
