package com.ivucenter.cloud.api.nutanix;

public enum NutanixType {
	VM_LIST, VM, VM_DISK, PROPERTIES, VM_NIC, TASK, BLUEPRINT, BLUEPRINT_LIST, BLUEPRINT_RESOURCE,
	BLUEPRINT_RUNTIME_EDITABLES, RESULT, BLUEPRINT_STATUS, APP, PROJECT, ACCOUNT, SUBNET, ENVIRONMENT, MARKETPLACE_ITEM,
}
